blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    path('tag/<str:tag_name>/', blog_view, name='tag'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    tag = TaggableManager()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return "{} - {}".format(self.title, self.id)

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Category, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse, resolve, Resolver404
from django.http import HttpResponseRedirect
import datetime
from blog.management import *


def blog_view(request, **kwargs):
    check_status()

    posts = Post.objects.exclude(published_date__gt=datetime.datetime.now())
    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') is not None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tag__name__in=[kwargs['tag_name']])
    posts = Paginator(posts, 3)

    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    all_cats = Category.objects.all()
    context = context = {'posts': posts, 'all_cats': all_cats}
    return render(request, 'blog/blog-home/blog-home.html', context)


def blog_single_view(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Your comment will be shown if approved")
        else:
            messages.add_message(request, messages.ERROR, "your comment didn't submited")
    # In this section, a number is added to the view variable for each view.
    add_counted_views(pid)
    # In this section, a complete list of posts is prepared
    posts_list = set_posts_list()
    # Post, previous post and next post are defined in the same way by default.
    post = get_object_or_404(Post, pk=pid, status=1)
    next_post = get_object_or_404(Post, pk=pid, status=1)
    previous_post = get_object_or_404(Post, pk=pid, status=1)
    # In this section, the has_previous_post and has_next_post variables are defined as false by default.
    has_previous_post = False
    has_next_post = False
    # In this section, the exact location of the post can be found in the list of all posts
    index_post = get_index_post(post.title)
    # In this section, it is determined whether there is a next post or not.
    if has_next_index(index_post):
        ''' 
            If there is, the has_next_post variable is declared true and
            the post whose position is 1 higher in the list from the complete list of posts
            is stored in the next_post variable.
        '''
        has_next_post = True
        next_post = posts_list[index_post + 1]

    # In this section, it is determined whether there is a previous post or not.
    if has_previous_index(post):
        '''
            If present, the has_previous_post variable is declared true and
            A post whose position in the list is 1 lower than the complete list of posts
            It is stored in the previous_post variable.
        '''
        has_previous_post = True
        previous_post = posts_list[index_post - 1]

    if not post.login_require:
        all_cats = Category.objects.all()
        comments = Comment.objects.filter(post=post.id, approved=True)
        form = CommentForm()
        context = {'post': post, 'all_cats': all_cats,
                   'next_post': next_post, 'has_next_post': has_next_post,
                   'previous_post': previous_post, 'has_previous_post': has_previous_post,
                   'comments': comments, 'form': form}
        return render(request, 'blog/blog-single/blog-single.html', context)

    elif request.user.is_authenticated:
        all_cats = Category.objects.all()
        comments = Comment.objects.filter(post=post.id, approved=True)
        form = CommentForm()
        context = {'post': post, 'all_cats': all_cats,
                   'next_post': next_post, 'has_next_post': has_next_post,
                   'previous_post': previous_post, 'has_previous_post': has_previous_post,
                   'comments': comments, 'form': form}
        return render(request, 'blog/blog-single/blog-single.html', context)

    else:
        return HttpResponseRedirect('{}?next={}{}'.format(reverse('accounts:login'), reverse('blog:index'), post.id))



def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains=s)

    context = {'posts': posts}
    return render(request, 'blog/blog-home/blog-home.html', context)

templates/blog/blog-single/blog-comment-area.html
{% load static %}
{% load humanize %}
<div class="comments-area">
    <h4>{{comments|length}} Comments</h4>
    {% for comment in comments %}
        <div class="comment-list">
            <div class="single-comment justify-content-between d-flex">
                <div class="user justify-content-between d-flex">
                    <div class="thumb">
                        <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                    </div>
                    <div class="desc">
                        <h5><a>{{comment.name}}</a></h5>
                        <p class="date">{{comment.updated_date|naturalday}}</p>
                        <p class="comment">
                            {{comment.message}}
                        </p>
                    </div>
                </div>
                <!--
                <div class="reply-btn">
                    <a href="" class="btn-reply text-uppercase">reply</a>
                </div>
                -->
            </div>
        </div>
        {% empty %}
        <p> no commments here be the first one </p>
    {% endfor %}
    <!-- <div class="comment-list left-padding">
        <div class="single-comment justify-content-between d-flex">
            <div class="user justify-content-between d-flex">
                <div class="thumb">
                    <img src="{% static 'img/blog/c2.jpg' %}" alt="">
                </div>
                <div class="desc">
                    <h5><a href="#">Elsie Cunningham</a></h5>
                    <p class="date">December 4, 2017 at 3:12 pm </p>
                    <p class="comment">
                        Never say goodbye till the end comes!
                    </p>
                </div>
            </div>
            <div class="reply-btn">
                <a href="" class="btn-reply text-uppercase">reply</a>
            </div>
        </div>
    </div> -->
</div>

templates/blog/blog-single/blog-comment-form-area.html
{% load static %}
<div class="comment-form">
  <h4>Leave a Comment</h4>
  <form method="post" action="{% url 'blog:single' pid=post.id %}">
    {% csrf_token %}
    <input type="hidden" name="post" value="{{post.id}}">
    {% if request.user.is_authenticated %}
    <input type="hidden" name="name" value="{{request.user.first_name}}">
    <input type="hidden" name="email" value="{{request.user.email}}">
    {% else %}
    <div class="form-group form-inline">
      <div class="form-group col-lg-6 col-md-12 name">
        <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'" required="">
      </div>
      <div class="form-group col-lg-6 col-md-12 email">
        <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" required="">
      </div>
    </div>
    {% endif %}
    <div class="form-group">
      <input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" required="">
    </div>
    <div class="form-group">
      <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
    </div>
    <button type="submit" class="primary-btn text-uppercase">Post Comment</button>
  </form>
  {% include 'messages.html' %}
</div>

templates/blog/blog-single/blog-single-banner-area.html
{% load static %}
<section class="relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    {{post.title}}
                </h1>
                <p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span> <a href="{% url 'blog:single' pid=post.id %}">
                    {{post.title}}</a></p>
            </div>
        </div>
    </div>
</section>

templates/blog/blog-single/blog-single-post-content-area.html
{% load static %}
{% load blog_tags %}
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}, </a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a>{{post.published_date|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a>{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a>{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
										{{post.content|safe}}
									</p>
								</div>
								<div class="col-lg-12">
									<div class="quotes">
									</div>
									<div class="row mt-30 mb-30">
										<div class="col-6">
											<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
										</div>
										<div class="col-6">
											<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
										</div>
									</div>
								</div>
							</div>
							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
									 	{% if has_previous_post == 1 %}
											<div class="thumb">
												<a href="{% url 'blog:single' pid=previous_post.id %}"><img class="img-fl" src="{{previous_post.image.url}}" alt=""></a>
											</div>
											<div class="arrow">
												<a href="{% url 'blog:single' pid=previous_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
											</div>
											<div class="detials">
												<p>Prev Post</p>
												<a href="{% url 'blog:single' pid=previous_post.id %}"><h4>{{previous_post.title}}</h4></a>
											</div>
										{% endif %}
									</div>
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										{% if has_next_post == 1 %}
											<div class="detials">
												<p>Next Post</p>
												<a href="{% url 'blog:single' pid=next_post.id %}"><h4>{{next_post.title}}</h4></a>
											</div>
											<div class="arrow">
												<a href="{% url 'blog:single' pid=next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
											</div>
											<div class="thumb">
												<a href="{% url 'blog:single' pid=next_post.id %}"><img class="img-fl" src="{{next_post.image.url}}" alt=""></a>
											</div>
										{% endif %}
									</div>
								</div>
							</div>
							{% include 'blog/blog-single/blog-comment-area.html' %}
							{% include 'blog/blog-single/blog-comment-form-area.html' %}
						</div>
							<div class="col-lg-4 sidebar-widgets">
								<div class="widget-wrap">
								   <div class="single-sidebar-widget search-widget">
									  <form class="search-form" action="{% url 'blog:search' %}">
										 <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
										 <button type="submit"><i class="fa fa-search"></i></button>
									  </form>
								   </div>
								   {% lastestposts %}
								   <div class="single-sidebar-widget ads-widget">
									  <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
								   </div>
								   {% postcategories %}
								   <div class="single-sidebar-widget newsletter-widget">
									  <h4 class="newsletter-title">Newsletter</h4>
									  <p>
										 Here, I focus on a range of items and features that we use in life without
										 giving them a second thought.
									  </p>
									  <div class="form-group d-flex flex-row">
										 <div class="col-autos">
											<div class="input-group">
											   <div class="input-group-prepend">
												  <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
												  </div>
											   </div>
											   <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
											</div>
										 </div>
										 <a href="#" class="bbtns">Subcribe</a>
									  </div>
									  <p class="text-bottom">
										 You can unsubscribe at any time
									  </p>
								   </div>
									 {% include 'blog/blog-single/blog-tags.html' %}
								</div>
							</div>
						</div>
			</div>
</section>

templates/blog/blog-single/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
			<!-- Start banner Area -->
			{% include 'blog/blog-single/blog-single-banner-area.html' %}
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			{% include 'blog/blog-single/blog-single-post-content-area.html' %}
			<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-single/blog-tags.html
{% load static %}
       <div class="single-sidebar-widget tag-cloud-widget">
          <h4 class="tagcloud-title">Tag Clouds</h4>
          <ul>
             {% for tag in post.tag.all %}
               <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
             {% endfor %}
          </ul>
       </div>